### ISSUE TITLE
can't launch: invalid literal for int() with base 16: ''

### ISSUE THREAD

**Issue by MuscularPuky** [Satanarious/TranslucentFlyoutsConfig#30]
Traceback (most recent call last):
  File "main.py", line 117, in <module>
  File "main.py", line 53, in __init__
  File "Data\user.py", line 129, in updateUI
  File "Widgets\color_picker.py", line 23, in changeButtonColor
  File "Widgets\color_picker.py", line 67, in aarrggbb_to_rgba
ValueError: invalid literal for int() with base 16: ''

Windows vNext NT 10.0.25997.1010

**Comment by MuscularPuky** [comment]
oh sry I didn't read the manual at all :(
[TranslucentFlyouts v2.1.txt](https://github.com/Satanarious/TransparentFlyoutsConfig/files/13540278/TranslucentFlyouts.v2.1.txt)

**Comment by Satanarious** [comment]
You should probably delete the `/TranslucentFlyouts` key and then try and open TFConfig. Hope it works for you.

**Comment by Satanarious** [comment]
> +TFMain64.dll is not found even it's already in the specified path. How can I migration existing configs? Should I uninstall TF?

I can see most of the key names are wrong in your registry. Since the UI is pretty intuitive, you should start from scratch if you are having problems with the existing configs. 

As for the TFMain64.dll not being found, I suggest checking the path again and clicking the save button after selecting the path. If it still doesn't work, I don't think I have a solution as of now. I tested it a minute ago, and the path selection is working fine. A second option would be to use the `Download and Install` button in the `External Functions` section. That should fix your problem, if not the formerly mentioned solution. 

Note: Just make sure to uninstall the previously installed TFs before using the `Download and Install` button.
