### ISSUE TITLE
"!! Error: TFMain64.dll not found !!" despite correct Installation Location

### ISSUE THREAD

**Issue by e-t-l** [Satanarious/TranslucentFlyoutsConfig#40]
I have Installation Location set to the correct directory, and the TFMain64.dll file is definitely present, yet I continue to get the error message `!! Error: TFMain64.dll not found !!`

--
TranslucentFlyoutsConfig v1.3.2
TranslucentFlyouts v2.1.0 x64
Windows 11 Enterprise x64

**Comment by Satanarious** [comment]
I'm out for the holidays. Will definitely look inti this as soon as I come back.

**Comment by Satanarious** [comment]
Could you confirm the following:
- Does it show the error even after pressing the save button?
- Are the internal functions working?
- Is the external function (Download and Install) working?

**Comment by TechySC23** [comment]
@Satanarious This happens to me too. After I press the save button. It;s okay but when I shutdown and open it, says the same thing.

**Comment by Satanarious** [comment]
> @Satanarious This happens to me too. After I press the save button. It;s okay but when I shutdown and open it, says the same thing.

Its a bug, will work regardless. I fixed it in #42 . Wait for next the release. Let me know if it doesn't work while showing the error.

**Comment by TechySC23** [comment]
BTW installed it again and works!

**Comment by TechySC23** [comment]
No Problem Sent from Mail for Windows From: Satyam Singh NiranjanSent: 29 February 2024 06:11 PMTo: Satanarious/TranslucentFlyoutsConfigCc: Shreyas Chatterjee; CommentSubject: Re: [Satanarious/TranslucentFlyoutsConfig] "!! Error: TFMain64.dll not found !!" despite correct Installation Location (Issue #40) Closed #40 as completed.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by Satanarious** [comment]
What is this supposed to be?

**Comment by Dhyfer1** [comment]
@Satanarious I also had the same problem as the OP but it is now solved. Of the two installation options: Rexcommended and Manual, I had to choose the Manual option because the other option is not working.

I mean, at first I selected the Recommended option and followed the steps as described (before that I uninstalled TranslucentFlyouts and removed the residual files as mentioned by the author), but after clicking on the Download and Install button in External Functions, TranslucentFlyoutsConfig stays on screen for a few seconds and then closes by itself.

And when I open TranslucentFlyoutsConfig again to see if it is installed, the Installation Location field under General remains empty, even if I click on Download and Install a second and third time.

So the Recommended option is not working, it is not downloading any files. So I had to reinstall TranslucentFlyouts and work with the manual installation of TranslucentFlyoutsConfig which did work for me.

**Comment by Satanarious** [comment]
What version are you using?

**Comment by Dhyfer1** [comment]
The latest version 1.3.5

**Comment by Satanarious** [comment]
Oh alright! I'm working on v1.4.0 right now. Can you make a new issue regarding this? Consider this fixed in the next release. The next release will completely support TF v3.0.0+ and everything it has to offer, including changes that broke TFC.

**Comment by Dhyfer1** [comment]
Ok, I will create a new issue about the mentioned problem, I am waiting for the next version 1.4.0 asap :D
